import Head from "next/head";
import Image from "next/image";
import Link from "next/link";


// import Link from "next/link";

import Logo from '../img/whitelogo.png'
import Home2 from "./Home2";



export default function Home() {
	

		
		
	return (
		<>
			<Head>
				<title>Storm Accessories</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/whitelogo.png" sizes="32x32" />
			</Head>
		

		<Home2/>
		</>
	);
}
